# Generated by Django 3.0.3 on 2020-05-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0002_auto_20200510_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='query_image',
            field=models.ImageField(blank=True, null=True, upload_to='Query_pics'),
        ),
    ]
