# Generated by Django 3.0.3 on 2020-05-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0004_auto_20200510_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='queryimage',
            new_name='image',
        ),
    ]
