# Generated by Django 3.0.3 on 2020-05-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0008_auto_20200511_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
