# Generated by Django 3.0.3 on 2020-05-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0009_remove_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Active',
            new_name='approved_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Parent',
        ),
    ]
